demo_demo:
    resource: "@DemoBundle/Resources/config/routing/demo.yml"


demo_homepage:
    path:     /hello/{name}
    defaults: { _controller: DemoBundle:Default:index }

demo_annotations:
    resource: "@DemoBundle/Controller/DemoController.php"
    type:     annotation