services:

     demo_report_manager:
             class: Edison\DemoBundle\Reporting\DemoReportManager
             arguments: ["@doctrine.orm.entity_manager", "@router"]

     twig.demo_extension:
             class: Edison\DemoBundle\Twig\DemoExtension
             arguments: []
             tags:
                - { name: twig.extension }