demo:
    resource: "@DemoBundle/Resources/config/routing.yml"
    prefix:   /

user_routes:
    resource: "@UserBundle/Controller"
    type: annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
