#demo:
   # path:     /
   # defaults: { _controller: "DemoBundle:Demo:index" }

demo_show:
    path:     /{slug}/show
    defaults: { _controller: "DemoBundle:Demo:show" }

demo_new:
    path:     /new
    defaults: { _controller: "DemoBundle:Demo:new" }

demo_create:
    path:     /create
    defaults: { _controller: "DemoBundle:Demo:create" }
    methods:  POST

demo_edit:
    path:     /{id}/edit
    defaults: { _controller: "DemoBundle:Demo:edit" }

demo_update:
    path:     /{id}/update
    defaults: { _controller: "DemoBundle:Demo:update" }
    methods:  [POST, PUT]

demo_delete:
    path:     /{id}/delete
    defaults: { _controller: "DemoBundle:Demo:delete" }
    methods:  [POST, DELETE]

demo_likes:
    path:      /{id}/likes.{format}
    defaults:  { _controller: "DemoBundle:Demo:likes", format: html }
    requirements:
         format: json

demo_unlikes:
    path:      /{id}/unlikes.{format}
    defaults:  { _controller: "DemoBundle:Demo:unlikes", format: html }
    requirements:
             format: json
